### ISSUE TITLE
Intermediate bounds for gradient nodes

### ISSUE THREAD

**Issue by nhamlv-55** [Verified-Intelligence/auto_LiRPA#48]
Hello,
When I iterate over all the nodes using this
```
lirpa_model = BoundedModel(my_pytorch_model, input)
lirpa_model.augment_gradient_graph(input)

for n in lirpa_model._modules.values():
    if hasattr(node, 'lower'):
        print(n, n.lower, n.upper)
    else:
        print(n, "this node doesnt have lower bound info")
```
Seems like many nodes do not have the lower and upper data, in particular, all gradient nodes (except the one for the original input) seem to not have it?
Is there a flag somewhere that I can set to retain that information? I assume that since the bounds for the gradient of the input with respect to the output are computed just fine, all the intermediate gradient nodes should have computed bound somewhere?
Many thanks.

**Comment by shizhouxing** [comment]
I think you need to call `compute_jacobian_bounds` after calling `augment_gradient_graph`. See: https://github.com/Verified-Intelligence/auto_LiRPA/blob/d2592c13198e0eb536967186758c264604b59539/examples/vision/jacobian.py#L72-L81 
Otherwise the bounds have not been computed yet. 

Still not all the nodes may have `.lower` and `.upper` if they are not necessary for the final results. See: https://github.com/Verified-Intelligence/auto_LiRPA/issues/46. In the future we may add an option allowing users to specify which nodes must be bounded regardless of whether they are needed for the final bounds.

**Comment by nhamlv-55** [comment]
@shizhouxing Thanks. Your suggestion in #46 works! I will close the issue.
