### ISSUE TITLE
AssertionError Triggered in LiRPA with YOLO-seg-v8

### ISSUE THREAD

**Issue by aknirala** [Verified-Intelligence/auto_LiRPA#77]
Title: AssertionError Triggered in LiRPA with YOLO-seg-v8

I am assessing the robustness of YOLO-seg-v8. Since passing the entire YOLO model to LiRPA isn't working, I started by passing the first three layers of YOLO to LiRPA. Unfortunately, LiRPA failed to create a BoundedModule for these layers. You can find the issue reproduced in this [Colab notebook](https://colab.research.google.com/drive/1UlVzJ2fSEM_ZwJyX0QX6lbny7ti7fSn1?usp=sharing).

The first three layers are:
- ultralytics.nn.modules.conv.Conv (Implemented [here](https://github.com/ultralytics/ultralytics/blob/abd391b63338b79cebee808b6679498dcc94956f/ultralytics/nn/modules/conv.py#L36))
- ultralytics.nn.modules.conv.Conv
- ultralytics.nn.modules.block.C2f  (implemented [here](https://github.com/ultralytics/ultralytics/blob/abd391b63338b79cebee808b6679498dcc94956f/ultralytics/nn/modules/block.py#L223))

The C2f layer involves some list processing, which I initially suspected to be the issue. However, creating a simple model using nn.ModuleList works fine (Also included in the colab)

Could you please help me understand why I am encountering this error? Any assistance is greatly appreciated.

**Comment by shizhouxing** [comment]
Hi @aknirala , according to your colab notebook, it looks like the issue is because the `onnx::Slice` operator is partially supported in auto_LiRPA, conditioned on `(steps == 1 or steps == -1) and axes == int(axes) and start == int(start) and end == int(end)`. `yolo_model.model.model[2]` may contain an `onnx::Slice` operator which does not satisfy the aforementioned above. You may also try modifying the `/usr/local/lib/python3.10/dist-packages/auto_LiRPA/operators/slice_concat.py` file to print more detailed information there and see which specific condition is violated. The most convenient fix for the issue will be to use a model which only consists of supported operators, like the one with nn.ModuleList you showed in the colab notebook.
